ranks:
  admin: "&4[Admin]"
  moderator: "&2[Moderator]"
  friend: "&8[Friend]"

players:
  UnOwly: admin

timber:
  enabled: []

chunkloader:
  skin:
    texture: "URL_TO_TEXTURE"
    signature: "TEXTURE_SIGNATURE"

spawner:
  break:
    enabled: true