name: oneplugin
version: 'BETA-1.0'
main: dev.unowly.oneplugin.OnePlugin
api-version: '1.21'
commands:
  setrank:
    description: Set rank of a player
    usage: /setrank <player> <rank>
  timber:
    description: Toggles den Timber-Mode
    usage: /timber
  loadchunk:
    description: Loads a chunk permanently.
    usage: /loadchunk
  unloadchunk:
    description: Unloads a previously loaded chunk.
    usage: /unloadchunk
  togglespawnerbreak:
    description: Toggles whether spawners can be broken.
    usage: /togglespawnerbreak